import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class CityService {
  options = [
    'Aaronsburg',
    'Abbottstown',
    'Aberdeen',
    'Abilene',
    'Adamsburg',
    'Adamstown',
    'Adamsville',
    'Addison',
    'Akron',
    'Alba',
    'Albany',
    'Albion',
    'Albuquerque',
    'Alburtis',
    'Aldan',
    'Alexandria',
    'Aliquippa',
    'Allenport',
    'Allentown',
    'Almedia',
    'Altamont',
    'Altoona',
    'Amarillo',
    'Ambler',
    'Ambridge',
    'Amity Gardens',
    'Anaheim',
    'Anchorage',
    'Ancient Oaks',
    'Ann Arbor',
    'Annville',
    'Antioch',
    'Apollo',
    'Apple Valley',
    'Appleton',
    'Applewold',
    'Archbald',
    'Ardmore',
    'Arendtsville',
    'Aristes',
    'Arlington',
    'Arlington Heights',
    'Armagh',
    'Arnold',
    'Arona',
    'Arvada',
    'Asheville',
    'Ashland',
    'Ashley',
    'Ashville',
    'Aspinwall',
    'Atglen',
    'Athens',
    'Atlanta',
    'Atlantic',
    'Atlantic City',
    'Atwood',
    'Auburn',
    'Audubon',
    'Augusta',
    'Aurora',
    'Austin',
    'Avalon',
    'Avis',
    'Avoca',
    'Avon',
    'Avondale',
    'Avonia',
    'Avonmore',
    'Back Mountain',
    'Baden',
    'Baidland',
    'Bakersfield',
    'Baldwin',
    'Bally',
    'Baltimore',
    'Bangor',
    'Barkeyville',
    'Barnstable',
    'Bath',
    'Baton Rouge',
    'Beallsville',
    'Bear Creek Village',
    'Bear Lake',
    'Beaumont',
    'Beaver',
    'Beaver Falls',
    'Beaver Meadows',
    'Beaver Springs',
    'Beaverdale-Lloydell',
    'Beavertown',
    'Bechtelsville',
    'Bedford',
    'Beech Creek',
    'Bel Air',
    'Belfast',
    'Bell Acres',
    'Belle Vernon',
    'Bellefonte',
    'Belleville',
    'Bellevue',
    'Bellwood',
    'Belmont',
    'Ben Avon',
    'Ben Avon Heights',
    'Bendersville',
    'Bendersville Station-Aspers',
    'Benson',
    'Bentleyville',
    'Benton',
    'Berkeley',
    'Berlin',
    'Bernville',
    'Berrysburg',
    'Berwick',
    'Bessemer',
    'Bethany',
    'Bethel Park',
    'Bethlehem',
    'Beurys Lake',
    'Big Beaver',
    'Big Run',
    'Biglerville',
    'Billings',
    'Birdsboro',
    'Birmingham',
    'Black Lick',
    'Blain',
    'Blairsville',
    'Blakely',
    'Blanchard',
    'Blawnox',
    'Bloomfield',
    'Blooming Valley',
    'Bloomington',
    'Bloomsburg',
    'Blossburg',
    'Blue Bell',
    'Boalsburg',
    'Boiling Springs',
    'Boise',
    'Boise City',
    'Bolivar',
    'Bonita Springs',
    'Bonneauville',
    'Boothwyn',
    'Boston',
    'Boswell',
    'Boulder',
    'Bowmanstown',
    'Boyertown',
    'Brackenridge',
    'Braddock',
    'Braddock Hills',
    'Bradenton',
    'Bradford',
    'Bradfordwoods',
    'Branchdale',
    'Brandonville',
    'Bremerton',
    'Brentwood',
    'Bressler-Enhaut-Oberlin',
    'Briar Creek',
    'Brickerville',
    'Bridgeport',
    'Bridgeville',
    'Bridgewater',
    'Brighton',
    'Brisbin',
    'Bristol',
    'Brittany Farms-Highlands',
    'Broad Top City',
    'Brockway',
    'Brodheadsville',
    'Brookhaven',
    'Brookville',
    'Broomall',
    'Brownstown',
    'Brownsville',
    'Bruin',
    'Bryan',
    'Bryn Athyn',
    'Bryn Mawr',
    'Buck Run',
    'Buckhorn',
    'Buffalo',
    'Burbank',
    'Burgettstown',
    'Burlington',
    'Burnham',
    'Burnside',
    'Butler',
    'California',
    'Callensburg',
    'Callery',
    'Callimont',
    'Calumet-Norvelt',
    'Cambridge',
    'Cambridge Springs',
    'Camp Hill',
    'Campbelltown',
    'Canadohta Lake',
    'Canonsburg',
    'Canton',
    'Cape Coral',
    'Carbondale',
    'Carlisle',
    'Carmichaels',
    'Carnegie',
    'Carnot-Moon',
    'Carroll Valley',
    'Carrollton',
    'Carrolltown',
    'Cary',
    'Cashtown-McKnightstown',
    'Cassandra',
    'Casselman',
    'Cassville',
    'Castanea',
    'Castle Shannon',
    'Catasauqua',
    'Catawissa',
    'Cathedral City',
    'Cecil-Bishop',
    'Cedar Rapids',
    'Centerport',
    'Centerville (Crawford County)',
    'Centerville (Washington County)',
    'Central City',
    'Centralia',
    'Centre Hall',
    'Chalfant',
    'Chalfont',
    'Chambersburg',
    'Champaign',
    'Chandler',
    'Chapman',
    'Charleroi',
    'Charleston',
    'Charlotte',
    'Chattanooga',
    'Cherry Tree',
    'Cherry Valley',
    'Chesapeake',
    'Chest Springs',
    'Chester',
    'Chester Heights',
    'Chester Hill',
    'Chester Township',
    'Chesterbrook',
    'Cheswick',
    'Chevy Chase Heights',
    'Chicago',
    'Chicora',
    'Christiana',
    'Chula Vista',
    'Churchill',
    'Churchville',
    'Cincinnati',
    'Clairton',
    'Clarence',
    'Clarendon',
    'Clarion',
    'Clark',
    'Clarke County',
    'Clarks Green',
    'Clarks Summit',
    'Clarksville',
    'Claysburg',
    'Claysville',
    'Clearfield',
    'Clearwater',
    'Cleona',
    'Cleveland',
    'Clifton Heights',
    'Clintonville',
    'Clymer',
    'Coal Center',
    'Coaldale (Bedford County)',
    'Coaldale (Schuylkill County)',
    'Coalmont',
    'Coalport',
    'Coatesville',
    'Coburn',
    'Cochranton',
    'Cokeburg',
    'College Station',
    'Collegeville',
    'Collingdale',
    'Colonial Park',
    'Colorado Springs',
    'Columbia',
    'Columbus',
    'Colver',
    'Colwyn',
    'Commodore',
    'Concord',
    'Confluence',
    'Conneaut Lake',
    'Conneaut Lakeshore',
    'Conneautville',
    'Connellsville',
    'Connoquenessing',
    'Conshohocken',
    'Conway',
    'Conyngham',
    'Coopersburg',
    'Cooperstown',
    'Coplay',
    'Coral Springs',
    'Coraopolis',
    'Cornwall',
    'Cornwells Heights-Eddington',
    'Corona',
    'Corpus Christi',
    'Corry',
    'Corsica',
    'Costa Mesa',
    'Coudersport',
    'Courtdale',
    'Crabtree',
    'Crafton',
    'Cranesville',
    'Creekside',
    'Cresson',
    'Cressona',
    'Cross Roads',
    'Croydon',
    'Curtisville',
    'Curwensville',
    'Daisytown',
    'Dale',
    'Dallas',
    'Dallastown',
    'Dalton',
    'Daly City',
    'Danbury',
    'Danville',
    'Darby',
    'Darby Township',
    'Darlington',
    'Dauphin',
    'Davenport',
    'Davidson County',
    'Davidsville',
    'Dawson',
    'Dayton',
    'Daytona Beach',
    'Deemston',
    'Deer Lake',
    'Delano',
    'Delaware Water Gap',
    'Delmont',
    'Delta',
    'Deltona',
    'Denton',
    'Denver',
    'Derry',
    'Des Moines',
    'Detroit',
    'Devon-Berwyn',
    'Dickson City',
    'Dicksonville',
    'Dillsburg',
    'Donaldson',
    'Donegal',
    'Donora',
    'Dormont',
    'Dover',
    'Downey',
    'Downingtown',
    'Doylestown',
    'Dravosburg',
    'Drexel Hill',
    'Driftwood',
    'Dublin',
    'DuBois',
    'Duboistown',
    'Dudley',
    'Duluth',
    'Dunbar',
    'Duncannon',
    'Duncansville',
    'Dunlevy',
    'Dunmore',
    'Dunnstown',
    'Dupont',
    'Duquesne',
    'Durham',
    'Duryea',
    'Dushore',
    'Eagles Mere',
    'Eagleville',
    'East Bangor',
    'East Berlin',
    'East Berwick',
    'East Brady',
    'East Butler',
    'East Conemaugh',
    'East Greenville',
    'East Lansdowne',
    'East McKeesport',
    'East Norriton',
    'East Petersburg',
    'East Pittsburgh',
    'East Prospect',
    'East Rochester',
    'East Rutherford',
    'East Side',
    'East Stroudsburg',
    'East Uniontown',
    'East Vandergrift',
    'East Washington',
    'East York',
    'Eastlawn Gardens',
    'Easton',
    'Eastvale',
    'Eau Claire',
    'Ebensburg',
    'Economy',
    'Eddystone',
    'Edgewood',
    'Edgeworth',
    'Edinboro',
    'Edwardsville',
    'Ehrenfeld',
    'El Monte',
    'El Paso',
    'Elco',
    'Elderton',
    'Eldred',
    'Elgin',
    'Elim',
    'Elizabeth',
    'Elizabethtown',
    'Elizabethville',
    'Elk Grove',
    'Elkhart',
    'Elkland',
    'Ellport',
    'Ellsworth',
    'Ellwood City',
    'Elverson',
    'Elysburg',
    'Emigsville',
    'Emlenton',
    'Emmaus',
    'Emporium',
    'Emsworth',
    'Englewood',
    'Enola',
    'Enon Valley',
    'Ephrata',
    'Erie',
    'Ernest',
    'Escondido',
    'Espy',
    'Etna',
    'Eugene',
    'Evans City',
    'Evansburg',
    'Evansville',
    'Everett',
    'Everson',
    'Exeter',
    'Export',
    'Exton',
    'Eyers Grove',
    'Factoryville',
    'Fairchance',
    'Fairdale',
    'Fairfield',
    'Fairless Hills',
    'Fairview',
    'Fairview-Ferndale',
    'Falls Creek',
    'Fallston',
    'Fargo',
    'Farrell',
    'Fawn Grove',
    'Fayette City',
    'Fayetteville',
    'Feasterville-Trevose',
    'Felton',
    'Ferndale',
    'Fernville',
    'Fernway',
    'Finleyville',
    'Fitchburg',
    'Fleetwood',
    'Flemington',
    'Flint',
    'Flourtown',
    'Flying Hills',
    'Folcroft',
    'Folsom',
    'Fontana',
    'Ford City',
    'Ford Cliff',
    'Forest City',
    'Forest Hills',
    'Forksville',
    'Forrestville',
    'Fort Collins',
    'Fort Indiantown Gap',
    'Fort Lauderdale',
    'Fort Smith',
    'Fort Walton Beach',
    'Fort Washington',
    'Fort Wayne',
    'Fort Worth',
    'Forty Fort',
    'Foundryville',
    'Fountain Hill',
    'Fountain Springs',
    'Fox Chapel',
    'Fox Run',
    'Foxburg',
    'Frackville',
    'Frankfort Springs',
    'Franklin',
    'Franklin Park',
    'Franklintown',
    'Frederick',
    'Fredericksburg CDP (Crawford County)',
    'Fredericksburg CDP (Lebanon County)',
    'Fredericktown-Millsboro',
    'Fredonia',
    'Freeburg',
    'Freedom',
    'Freeland',
    'Freemansburg',
    'Freeport',
    'Fremont',
    'Fresno',
    'Friedens',
    'Friedensburg',
    'Friendsville',
    'Fullerton',
    'Gainesville',
    'Galeton',
    'Gallitzin',
    'Gap',
    'Garden Grove',
    'Garden View',
    'Garland',
    'Garrett',
    'Gastonia',
    'Gastonville',
    'Geistown',
    'Geneva',
    'Georgetown',
    'Gettysburg',
    'Gilbert',
    'Gilberton',
    'Gilbertsville',
    'Girard',
    'Girardville',
    'Glasgow',
    'Glassport',
    'Glen Campbell',
    'Glen Hope',
    'Glen Lyon',
    'Glen Rock',
    'Glenburn',
    'Glendale',
    'Glendon',
    'Glenfield',
    'Glenolden',
    'Glenside',
    'Goldsboro',
    'Gordon',
    'Grampian',
    'Grand Prairie',
    'Grand Rapids',
    'Grantley',
    'Grapeville',
    'Gratz',
    'Grayslake',
    'Great Bend',
    'Green Bay',
    'Green Hills',
    'Green Lane',
    'Green Tree',
    'GreenBay',
    'Greencastle',
    'Greensboro',
    'Greensburg',
    'Greenville',
    'Grier City-Park Crest',
    'Grindstone-Rowes Run',
    'Grove City',
    'Guilford',
    'Gulfport-Biloxi',
    'Guys Mills',
    'Hagerstown',
    'Halfway House',
    'Halifax',
    'Hallam',
    'Hallstead',
    'Hamburg',
    'Hampton',
    'Hampton Township',
    'Hanover',
    'Harleysville',
    'Harlingen',
    'Harmonsburg',
    'Harmony',
    'Harmony Township',
    'Harrisburg',
    'Harrison City',
    'Harrison Township',
    'Harrisville',
    'Hartford',
    'Hartleton',
    'Hartstown',
    'Harveys Lake',
    'Hasson Heights',
    'Hastings',
    'Hatboro',
    'Hatfield',
    'Havre de Grace',
    'Hawley',
    'Hawthorn',
    'Haysville',
    'Hayward',
    'Hazleton',
    'Heckscherville',
    'Heidelberg',
    'Heilwood',
    'Hellertown',
    'Hemet',
    'Henderson',
    'Herminie',
    'Hermitage',
    'Herndon',
    'Hershey',
    'Hesperia',
    'Hialeah',
    'Hickory',
    'High Point',
    'Highland Park',
    'Highspire',
    'Hiller',
    'Hokendauqua',
    'Hollidaysburg',
    'Hollywood',
    'Homeacre-Lyndora',
    'Homer City',
    'Homestead',
    'Hometown',
    'Homewood',
    'Honesdale',
    'Honey Brook',
    'Honolulu',
    'Hookstown',
    'Hooversville',
    'Hop Bottom',
    'Hopewell',
    'Hopwood',
    'Horsham',
    'Houma',
    'Houserville',
    'Houston',
    'Houtzdale',
    'Howard',
    'Howell',
    'Hughestown',
    'Hughesville',
    'Hulmeville',
    'Hummels Wharf',
    'Hummelstown',
    'Hunker',
    'Huntingdon',
    'Huntington',
    'Huntington Beach',
    'Huntsville',
    'Hyde',
    'Hyde Park',
    'Hydetown',
    'Hyndman',
    'Imperial-Enlow',
    'Independence',
    'Indian Lake',
    'Indiana',
    'Indianapolis',
    'Industry',
    'Inglewood',
    'Ingram',
    'Iola',
    'Irvine',
    'Irving',
    'Irvona',
    'Irwin',
    'Ivyland',
    'Jackson',
    'Jackson Center',
    'Jacksonville',
    'Jacobus',
    'Jamestown',
    'Jamison City',
    'Jeannette',
    'Jeddo',
    'Jefferson',
    'Jefferson (Greene County)',
    'Jefferson (York County)',
    'Jefferson Hills',
    'Jenkintown',
    'Jennerstown',
    'Jermyn',
    'Jerome',
    'Jersey City',
    'Jersey Shore',
    'Jerseytown',
    'Jessup',
    'Jim Thorpe',
    'Johnson City',
    'Johnsonburg',
    'Johnstown',
    'Joliet',
    'Jonestown',
    'Julian',
    'Juniata Terrace',
    'Kailua',
    'Kalamazoo',
    'Kane',
    'Kaneohe',
    'Kansas City',
    'Karns City',
    'Kenhorst',
    'Kenilworth',
    'Kennedy Township',
    'Kennett Square',
    'Kennewick',
    'Kenosha',
    'Killeen',
    'King of Prussia',
    'Kingston',
    'Kissimmee',
    'Kistler',
    'Kittanning',
    'Klingerstown',
    'Knox',
    'Knoxville',
    'Koppel',
    'Kratzerville',
    'Kreamer',
    'Kulpmont',
    'Kulpsville',
    'Kutztown',
    'Lacey',
    'Laceyville',
    'Lafayette',
    'Laflin',
    'Lake Charles',
    'Lake City',
    'Lake Heritage',
    'Lake Meade',
    'Lake Wynonah',
    'Lakeland',
    'Lakewood',
    'Lancaster',
    'Landingville',
    'Landisburg',
    'Lanesboro',
    'Langhorne',
    'Langhorne Manor',
    'Lansdale',
    'Lansdowne',
    'Lansford',
    'Lansing',
    'Laporte',
    'Laredo',
    'Larksville',
    'Las Cruces',
    'Las Vegas',
    'Latrobe',
    'Laurel Mountain',
    'Laurel Run',
    'Laureldale',
    'Lavelle-Locustdale',
    'Lawnton',
    'Lawrence Park',
    'Lawrenceville',
    'Lawson Heights',
    'Layton',
    'Le Raysville',
    'Leacock-Leola-Bareville',
    'Lebanon',
    'Lebanon South',
    'Leechburg',
    'Leesport',
    'Leetsdale',
    'Lehighton',
    'Leith-Hatfield',
    'Lemont',
    'Lemoyne',
    'Lenape Heights',
    'Lenhartsville',
    'Leominster',
    'Levittown',
    'Lewis Run',
    'Lewisberry',
    'Lewisburg',
    'Lewistown',
    'Lewisville',
    'Lexington',
    'Liberty (Allegheny County)',
    'Liberty (Tioga County)',
    'Lightstreet',
    'Ligonier',
    'Lilly',
    'Lima',
    'Lime Ridge',
    'Lincoln',
    'Lincolnville',
    'Linesville',
    'Linglestown',
    'Linntown',
    'Linwood',
    'Lionville-Marchwood',
    'Lititz',
    'Little Meadows',
    'Little Rock',
    'Littlestown',
    'Liverpool',
    'Lock Haven',
    'Locustdale',
    'Loganton',
    'Loganville',
    'Long Beach',
    'Long Branch',
    'Lorain',
    'Lorane',
    'Loretto',
    'Los Angeles',
    'Louisville',
    'Lowell',
    'Lower Allen',
    'Lower Burrell',
    'Lubbock',
    'Lucerne Mines',
    'Lumber City',
    'Luzerne',
    'Lykens',
    'Lynnwood-Pricedale',
    'Lyons',
    'Macon',
    'Macungie',
    'Madison',
    'Madisonburg',
    'Mahaffey',
    'Mahanoy City',
    'Mainville',
    'Malvern',
    'Manchester',
    'Manheim',
    'Manns Choice',
    'Manor',
    'Manorville',
    'Mansfield',
    'Maple Glen',
    'Mapleton',
    'Marcus Hook',
    'Marianna',
    'Marietta',
    'Marina',
    'Marion Center',
    'Marion Heights',
    'Marklesburg',
    'Markleysburg',
    'Marlin',
    'Mars',
    'Marshallton',
    'Martinsburg',
    'Marysville',
    'Masontown',
    'Matamoras',
    'Mayfield',
    'Maytown',
    'McAdoo',
    'McAlisterville',
    'McAllen',
    'McCandless Township',
    'McChesneytown-Loyalhanna',
    'McClure',
    'McConnellsburg',
    'McDonald',
    'McEwensville',
    'McGovern',
    'McHenry',
    'McKean',
    'McKeansburg',
    'McKees Rocks',
    'McKeesport',
    'McMurray',
    'McSherrystown',
    'McVeytown',
    'Meadowood',
    'Meadville',
    'Mechanicsburg',
    'Mechanicsville',
    'Medford',
    'Media',
    'Melbourne',
    'Memphis',
    'Merced',
    'Mercer',
    'Mercersburg',
    'Meridian',
    'Mesa',
    'Meshoppen',
    'Mesquite',
    'Mexico',
    'Meyersdale',
    'Miami',
    'Middleburg',
    'Middleport',
    'Middletown',
    'Midland',
    'Midway',
    'Mifflin',
    'Mifflinburg',
    'Mifflintown',
    'Mifflinville',
    'Milesburg',
    'Milford',
    'Mill Creek',
    'Mill Hall',
    'Mill Village',
    'Millbourne',
    'Millersburg',
    'Millerstown',
    'Millersville',
    'Millheim',
    'Millvale',
    'Millville',
    'Milroy',
    'Milton',
    'Milwaukee',
    'Minersville',
    'Minneapolis',
    'Miramar',
    'Mission Viejo',
    'Mobile',
    'Modena',
    'Modesto',
    'Mohnton',
    'Monaca',
    'Monessen',
    'Monongahela',
    'Monroe',
    'Monroeville',
    'Mont Alto',
    'Monterey',
    'Montgomery',
    'Montgomeryville',
    'Montoursville',
    'Montrose',
    'Monument',
    'Moosic',
    'Moreno Valley',
    'Morrisville',
    'Morton',
    'Moscow',
    'Mount Carbon',
    'Mount Carmel',
    'Mount Cobb',
    'Mount Gretna',
    'Mount Gretna Heights',
    'Mount Holly Springs',
    'Mount Jewett',
    'Mount Joy',
    'Mount Lebanon',
    'Mount Oliver',
    'Mount Penn',
    'Mount Pleasant',
    'Mount Pleasant Mills',
    'Mount Pocono',
    'Mount Union',
    'Mount Wolf',
    'Mountain Top',
    'Mountainhome',
    'Mountville',
    'Muncy',
    'Munhall',
    'Murfreesboro',
    'Murrieta',
    'Murrysville',
    'Muskegon',
    'Myerstown',
    'Myrtle Beach',
    'Nanticoke',
    'Nanty-Glo',
    'Naperville',
    'Naples',
    'Narberth',
    'Nashua',
    'Nashville',
    'Nazareth',
    'Nemacolin',
    'Nescopeck',
    'Nesquehoning',
    'Nether Providence Township',
    'New Albany',
    'New Alexandria',
    'New Baltimore',
    'New Beaver',
    'New Bedford',
    'New Berlin',
    'New Bethlehem',
    'New Boston-Morea',
    'New Brighton',
    'New Britain',
    'New Buffalo',
    'New Castle',
    'New Castle Northwest',
    'New Centerville',
    'New Columbus',
    'New Cumberland',
    'New Eagle',
    'New Florence',
    'New Freedom',
    'New Galilee',
    'New Haven',
    'New Holland',
    'New Hope',
    'New Kensington',
    'New Kingstown',
    'New Lebanon',
    'New London',
    'New Milford',
    'New Morgan',
    'New Orleans',
    'New Oxford',
    'New Paris',
    'New Philadelphia',
    'New Ringgold',
    'New Salem',
    'New Salem-Buffington',
    'New Stanton',
    'New Washington',
    'New Wilmington',
    'New York',
    'New York City',
    'Newark',
    'Newburg (Clearfield County)',
    'Newburg (Cumberland County)',
    'Newburgh',
    'Newell',
    'Newmanstown',
    'Newport',
    'Newport News',
    'Newry',
    'Newton Hamilton',
    'Newtown',
    'Newtown Grant',
    'Newville',
    'Nicholson',
    'Nixon',
    'Norfolk',
    'Normal',
    'Norman',
    'Norristown',
    'North Apollo',
    'North Belle Vernon',
    'North Braddock',
    'North Catasauqua',
    'North Charleroi',
    'North Charleston',
    'North East',
    'North Irwin',
    'North Las Vegas',
    'North Philipsburg',
    'North Port',
    'North Vandergrift-Pleasant View',
    'North Versailles',
    'North Wales',
    'North York',
    'Northampton',
    'Northern Cambria',
    'Northumberland',
    'Northwest Harborcreek',
    'Norwalk',
    'Norwich',
    'Norwood',
    'Nuangola',
    'Numidia',
    'Nuremberg',
    'Oak Hills',
    'Oakdale',
    'Oakland',
    'Oakmont',
    'Oakwood',
    'Ocala',
    'Oceanside',
    'Odessa',
    'Ogden',
    'O\'Hara Township',
    'Ohiopyle',
    'Ohioville',
    'Oil City',
    'Oklahoma',
    'Oklahoma City',
    'Olathe',
    'Old Forge',
    'Old Orchard',
    'Oliver',
    'Olympia',
    'Olyphant',
    'Omaha',
    'Oneida',
    'Ontario',
    'Orange',
    'Orangeville',
    'Orbisonia',
    'Orchard Hills',
    'Oreland',
    'Orem',
    'Orlando',
    'Orrstown',
    'Orrtanna',
    'Orwigsburg',
    'Osborne',
    'Osceola Mills',
    'Oswayo',
    'Overland Park',
    'Oxford',
    'Oxnard',
    'Paint',
    'Palm Bay',
    'Palm Springs',
    'Palmdale',
    'Palmer Heights',
    'Palmerton',
    'Palmyra',
    'Palo Alto',
    'Panama City',
    'Paoli',
    'Paradise',
    'Park Forest Village',
    'Parker',
    'Parkesburg',
    'Parkside',
    'Parkville',
    'Parryville',
    'Pasadena',
    'Paterson',
    'Patterson Heights',
    'Patterson Township',
    'Patton',
    'Paxtang',
    'Paxtonia',
    'Paxtonville',
    'Pembroke Pines',
    'Pen Argyl',
    'Penbrook',
    'Penn',
    'Penn Hills',
    'Penn Lake Park',
    'Penn Wynne',
    'Penndel',
    'Penns Creek',
    'Pennsburg',
    'Pennsbury Village',
    'Pennville',
    'Pensacola',
    'Peoria',
    'Perkasie',
    'Perryopolis',
    'Petersburg',
    'Petrolia',
    'Philadelphia',
    'Philipsburg',
    'Phoenix',
    'Phoenixville',
    'Picture Rocks',
    'Pillow',
    'Pine Glen',
    'Pine Grove',
    'Pine Grove Mills',
    'Pitcairn',
    'Pittsburgh',
    'Pittston',
    'Plainfield',
    'Plano',
    'Platea',
    'Pleasant Gap',
    'Pleasant Hill',
    'Pleasant Hills',
    'Pleasantville (Bedford County)',
    'Pleasantville (Venango County)',
    'Plum',
    'Plumville',
    'Plymouth',
    'Plymouth Meeting',
    'Plymptonville',
    'Pocono Pines',
    'Point Marion',
    'Polk',
    'Pomona',
    'Pompano Beach',
    'Port Allegany',
    'Port Arthur',
    'Port Carbon',
    'Port Clinton',
    'Port Matilda',
    'Port Orange',
    'Port Royal',
    'Port Saint Lucie',
    'Port St. Lucie',
    'Port Trevorton',
    'Port Vue',
    'Portage',
    'Portersville',
    'Portland',
    'Portsmouth',
    'Pottsgrove',
    'Pottstown',
    'Pottsville',
    'Poughkeepsie',
    'Pringle',
    'Progress',
    'Prompton',
    'Prospect',
    'Prospect Park',
    'Providence',
    'Provo',
    'Pueblo',
    'Punta Gorda',
    'Punxsutawney',
    'Pymatuning Central',
    'Pymatuning North',
    'Pymatuning South',
    'Quakertown',
    'Quarryville',
    'Quentin',
    'Racine',
    'Radnor Township',
    'Railroad',
    'Rainsburg',
    'Raleigh',
    'Ramblewood',
    'Ramey',
    'Rancho Cucamonga',
    'Rankin',
    'Ravine',
    'Reading',
    'Reamstown',
    'Rebersburg',
    'Red Hill',
    'Red Lion',
    'Redding',
    'Reedsville',
    'Reiffton',
    'Reinerton-Orwin-Muir',
    'Renningers',
    'Reno',
    'Renovo',
    'Republic',
    'Reserve Township',
    'Reynoldsville',
    'Rheems',
    'Rices Landing',
    'Riceville',
    'Richboro',
    'Richfield',
    'Richland',
    'Richlandtown',
    'Richmond',
    'Richmond County',
    'Ridgway',
    'Ridley Park',
    'Riegelsville',
    'Rimersburg',
    'Ringtown',
    'Riverside',
    'Roanoke',
    'Roaring Spring',
    'Robesonia',
    'Robinson Township',
    'Rochester',
    'Rockford',
    'Rockhill Furnace',
    'Rockledge',
    'Rockwood',
    'Rohrsburg',
    'Rome',
    'Roscoe',
    'Rose Valley',
    'Roseto',
    'Roseville',
    'Ross Township',
    'Rossiter',
    'Rosslyn Farms',
    'Rothsville',
    'Round Lake Beach',
    'Rouseville',
    'Rouzerville',
    'Royalton',
    'Royersford',
    'Rupert',
    'Rural Valley',
    'Russellton',
    'Rutherford',
    'Rutledge',
    'S.N.P.J.',
    'Sacramento',
    'Saegertown',
    'Saginaw',
    'Saint Louis',
    'Saint Paul',
    'Saint Petersburg',
    'Salem',
    'Salinas',
    'Salisbury',
    'Salix-Beauty Line Park',
    'Salladasburg',
    'Salt Lake City',
    'Saltillo',
    'Saltsburg',
    'Salunga-Landisville',
    'San Antonio',
    'San Bernardino',
    'San Buenaventura',
    'San Diego',
    'San Francisco',
    'San Jose',
    'Sanatoga',
    'Sand Hill',
    'Sandy',
    'Sandy Lake',
    'Sandy Ridge',
    'Sankertown',
    'Santa Ana',
    'Santa Barbara',
    'Santa Clara',
    'Santa Clarita',
    'Santa Cruz',
    'Santa Maria',
    'Santa Rosa',
    'Sarasota',
    'Savannah',
    'Saxonburg',
    'Saxton',
    'Sayre',
    'Scalp Level',
    'Schaefferstown',
    'Schellsburg',
    'Schlusser',
    'Schnecksville',
    'Schuylkill Haven',
    'Schwenksville',
    'Scott Township',
    'Scottdale',
    'Scottsdale',
    'Scranton',
    'Seaside',
    'Seattle',
    'Sebastian',
    'Selinsgrove',
    'Sellersville',
    'Seltzer',
    'Seneca',
    'Seven Fields',
    'Seven Springs',
    'Seven Valleys',
    'Seward',
    'Sewickley',
    'Sewickley Heights',
    'Sewickley Hills',
    'Shade Gap',
    'Shaler Township',
    'Shamokin',
    'Shamokin Dam',
    'Shanksville',
    'Shanor-Northvue',
    'Sharon',
    'Sharon Hill',
    'Sharpsburg',
    'Sharpsville',
    'Sheakleyville',
    'Sheffield',
    'Shelocta',
    'Shenandoah',
    'Shenandoah Heights',
    'Sheppton',
    'Shickshinny',
    'Shillington',
    'Shiloh',
    'Shinglehouse',
    'Shippensburg',
    'Shippenville',
    'Shippingport',
    'Shiremanstown',
    'Shirleysburg',
    'Shoemakersville',
    'Shreveport',
    'Shrewsbury',
    'Silverdale',
    'Simi Valley',
    'Sinking Spring',
    'Sioux City',
    'Sioux Falls',
    'Skippack',
    'Skyline View',
    'Slabtown',
    'Slatington',
    'Slickville',
    'Sligo',
    'Slippery Rock',
    'Smethport',
    'Smicksburg',
    'Smithfield',
    'Smithton',
    'Snow Shoe',
    'Snydertown',
    'Somerset',
    'Souderton',
    'South Bend',
    'South Bethlehem',
    'South Coatesville',
    'South Connellsville',
    'South Fork',
    'South Greensburg',
    'South Heights',
    'South Lyon',
    'South New Castle',
    'South Park Township',
    'South Philipsburg',
    'South Pottstown',
    'South Renovo',
    'South Waverly',
    'South Williamsport',
    'Southmont',
    'Southwest Greensburg',
    'Spartanburg',
    'Spartansburg',
    'Speers',
    'Spokane',
    'Spring City',
    'Spring Grove',
    'Spring Hill',
    'Spring House',
    'Spring Mills',
    'Spring Mount',
    'Spring Ridge',
    'Springboro',
    'Springdale',
    'Springetts Manor-Yorklyn',
    'Springfield',
    'Spry',
    'St. Clair',
    'St. Clairsville',
    'St. Lawrence',
    'St. Louis',
    'St. Marys',
    'St. Michael-Sidman',
    'St. Paul',
    'St. Petersburg',
    'Stamford',
    'Starrucca',
    'State College',
    'Steelton',
    'Sterling Heights',
    'Stewartstown',
    'Stillwater',
    'Stockdale',
    'Stockertown',
    'Stockton',
    'Stoneboro',
    'Stonybrook-Wilshire',
    'Stormstown',
    'Stowe',
    'Stowe Township',
    'Stoystown',
    'Strasburg',
    'Strattanville',
    'Strausstown',
    'Stroudsburg',
    'Sturgeon-Noblestown',
    'Sugar Grove',
    'Sugar Notch',
    'Sugarcreek',
    'Summerhill',
    'Summerville',
    'Summit Hill',
    'Summit Station',
    'Sunbury',
    'Sunnyvale',
    'Susquehanna Depot',
    'Susquehanna Trails',
    'Sutersville',
    'Swarthmore',
    'Swissvale',
    'Swoyersville',
    'Sykesville',
    'Sylvania',
    'Syracuse',
    'Tacoma',
    'Tallahassee',
    'Tamaqua',
    'Tampa',
    'Tarentum',
    'Tatamy',
    'Taylor',
    'Telford',
    'Temecula',
    'Tempe',
    'Terre Hill',
    'Thompson',
    'Thompsontown',
    'Thompsonville',
    'Thornburg',
    'Thorndale',
    'Thornton',
    'Thousand Oaks',
    'Three Springs',
    'Throop',
    'Tidioute',
    'Timber Hills',
    'Timblin',
    'Tinicum Township',
    'Tioga',
    'Tionesta',
    'Tipton',
    'Titusville',
    'Toledo',
    'Topeka',
    'Topton',
    'Torrance',
    'Toughkenamon',
    'Towanda',
    'Tower City',
    'Townville',
    'Trafford',
    'Trainer',
    'Trappe',
    'Treasure Lake',
    'Tremont',
    'Trenton',
    'Tresckow',
    'Trevorton',
    'Trooper',
    'Troutville',
    'Troxelville',
    'Troy',
    'Trumbauersville',
    'Tucson',
    'Tullytown',
    'Tulsa',
    'Tunkhannock',
    'Tunnelhill',
    'Turbotville',
    'Turtle Creek',
    'Tuscaloosa',
    'Tuscarora',
    'Twilight',
    'Tyler',
    'Tyler Run-Queens Gate',
    'Tyrone',
    'Ulysses',
    'Union City',
    'Union Dale',
    'Uniontown',
    'Unionville',
    'Upland',
    'Upper Providence Township',
    'Upper St. Clair',
    'Ursina',
    'Utica',
    'Valencia',
    'Vallejo',
    'Valley Green',
    'Valley View CDP (Schuylkill County)',
    'Valley View CDP (York County)',
    'Valley-Hi',
    'Vancouver',
    'Vanderbilt',
    'Vandergrift',
    'Vandling',
    'Venango',
    'Vero Beach',
    'Verona',
    'Versailles',
    'Victorville',
    'Village Green-Green Ridge',
    'Village Shires',
    'Vinco',
    'Vintondale',
    'Virginia Beach',
    'Visalia',
    'Volant',
    'Waco',
    'Wall',
    'Wallaceton',
    'Waller',
    'Walnutport',
    'Wampum',
    'Warminster Heights',
    'Warren',
    'Warren South',
    'Warrior Run',
    'Washington',
    'Washingtonville',
    'Waterbury',
    'Waterford',
    'Waterloo',
    'Watsontown',
    'Wattsburg',
    'Waymart',
    'Wayne Heights',
    'Waynesboro',
    'Waynesburg',
    'Weatherly',
    'Weigelstown',
    'Weissport',
    'Weissport East',
    'Wellersburg',
    'Wellsboro',
    'Wellsville',
    'Wernersville',
    'Wesleyville',
    'West Alexander',
    'West Brownsville',
    'West Chester',
    'West Conshohocken',
    'West Covina',
    'West Easton',
    'West Elizabeth',
    'West Goshen',
    'West Grove',
    'West Hazleton',
    'West Hills',
    'West Homestead',
    'West Kittanning',
    'West Lawn',
    'West Leechburg',
    'West Liberty',
    'West Mayfield',
    'West Middlesex',
    'West Middletown',
    'West Mifflin',
    'West Newton',
    'West Norriton',
    'West Pittston',
    'West Reading',
    'West Sunbury',
    'West Valley City',
    'West View',
    'West Wyoming',
    'West Wyomissing',
    'West York',
    'Westfield',
    'Westminster',
    'Westmont',
    'Westover',
    'Wheatland',
    'Whitaker',
    'White Haven',
    'White Oak',
    'Whitehall',
    'Whitfield',
    'Wichita',
    'Wickerham Manor-Fisher',
    'Wilburton Number One',
    'Wilburton Number Two',
    'Wilkes-Barre',
    'Wilkes-Barre Township',
    'Wilkins Township',
    'Wilkinsburg',
    'Williamsburg',
    'Williamsport',
    'Williamstown',
    'Willow Grove',
    'Willow Street',
    'Wilmerding',
    'Wilmington',
    'Wilmore',
    'Wilson',
    'Wind Gap',
    'Windber',
    'Windsor',
    'Winston',
    'Winter Haven',
    'Winterstown',
    'Wolfdale',
    'Womelsdorf',
    'Woodbourne',
    'Woodbury',
    'Woodcock',
    'Woodland Heights',
    'Woodlyn',
    'Woodside',
    'Woodward',
    'Worcester',
    'Wormleysburg',
    'Worthington',
    'Worthville',
    'Wrightsville',
    'Wyalusing',
    'Wyncote',
    'Wyndmoor',
    'Wyoming',
    'Wyomissing',
    'Wyomissing Hills',
    'Yakima',
    'Yardley',
    'Yatesville',
    'Yeadon',
    'Yeagertown',
    'Yoe',
    'Yonkers',
    'York',
    'York Haven',
    'York Springs',
    'Yorkana',
    'Youngstown',
    'Youngsville',
    'Youngwood',
    'Zelienople',
    'Zion'
  ];

  getAll(): Observable<string[]> {
    return of(this.options);
  }
}
